/*          Author: Mohamed Abdelgawad       */
/*          Date: 07-11-2023				 */
/*          Version: 1.0					 */
/*          Module: KEYPAD					 */

#include "../../MCAL/service/STD_types.h"
#include "../../MCAL/DIO/DIO_int.h"
#include "KEYPAD_config.h"
#include "KEYPAD_int.h"

void KEYPAD_voidInit(void)
{
	DIO_voidSetPinDir(KEYPAD_U8_COL_PORT,KEYPAD_U8_COL_1_PIN,DIO_U8_OUTPUT);
	DIO_voidSetPinDir(KEYPAD_U8_COL_PORT,KEYPAD_U8_COL_2_PIN,DIO_U8_OUTPUT);
	DIO_voidSetPinDir(KEYPAD_U8_COL_PORT,KEYPAD_U8_COL_3_PIN,DIO_U8_OUTPUT);
	DIO_voidSetPinDir(KEYPAD_U8_COL_PORT,KEYPAD_U8_COL_4_PIN,DIO_U8_OUTPUT);
	
	DIO_voidSetPinDir(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_1_PIN,DIO_U8_INPUT);
	DIO_voidSetPinDir(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_2_PIN,DIO_U8_INPUT);
	DIO_voidSetPinDir(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_3_PIN,DIO_U8_INPUT);
	DIO_voidSetPinDir(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_4_PIN,DIO_U8_INPUT);	
	
	DIO_voidSetPinVal(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_1_PIN,DIO_U8_HIGH);
	DIO_voidSetPinVal(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_2_PIN,DIO_U8_HIGH);
	DIO_voidSetPinVal(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_3_PIN,DIO_U8_HIGH);
	DIO_voidSetPinVal(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_4_PIN,DIO_U8_HIGH);	
	
	
	
}
u8 KEYPAD_u8GetButton(void)
{
	u8 LOCAL_u8Button = '\0';
	
	DIO_voidSetPinVal(KEYPAD_U8_COL_PORT,KEYPAD_U8_COL_1_PIN,DIO_U8_LOW);
	DIO_voidSetPinVal(KEYPAD_U8_COL_PORT,KEYPAD_U8_COL_2_PIN,DIO_U8_HIGH);
	DIO_voidSetPinVal(KEYPAD_U8_COL_PORT,KEYPAD_U8_COL_3_PIN,DIO_U8_HIGH);
	DIO_voidSetPinVal(KEYPAD_U8_COL_PORT,KEYPAD_U8_COL_4_PIN,DIO_U8_HIGH);
	if(DIO_u8GetPinVal(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_1_PIN) == DIO_U8_LOW)
	{
		LOCAL_u8Button = KEYPAD_U8_C1R1;
	}
	else if(DIO_u8GetPinVal(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_2_PIN) == DIO_U8_LOW)
	{
		LOCAL_u8Button = KEYPAD_U8_C1R2;
	}
	else if(DIO_u8GetPinVal(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_3_PIN) == DIO_U8_LOW)
	{
		LOCAL_u8Button = KEYPAD_U8_C1R3;
	}
	else if(DIO_u8GetPinVal(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_4_PIN) == DIO_U8_LOW)
	{
		LOCAL_u8Button = KEYPAD_U8_C1R4;
	}
	
	DIO_voidSetPinVal(KEYPAD_U8_COL_PORT,KEYPAD_U8_COL_1_PIN,DIO_U8_HIGH);
	DIO_voidSetPinVal(KEYPAD_U8_COL_PORT,KEYPAD_U8_COL_2_PIN,DIO_U8_LOW);
	DIO_voidSetPinVal(KEYPAD_U8_COL_PORT,KEYPAD_U8_COL_3_PIN,DIO_U8_HIGH);
	DIO_voidSetPinVal(KEYPAD_U8_COL_PORT,KEYPAD_U8_COL_4_PIN,DIO_U8_HIGH);
	if(DIO_u8GetPinVal(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_1_PIN) == DIO_U8_LOW)
	{
		LOCAL_u8Button = KEYPAD_U8_C2R1;
	}
	else if(DIO_u8GetPinVal(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_2_PIN) == DIO_U8_LOW)
	{
		LOCAL_u8Button = KEYPAD_U8_C2R2;
	}
	else if(DIO_u8GetPinVal(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_3_PIN) == DIO_U8_LOW)
	{
		LOCAL_u8Button = KEYPAD_U8_C2R3;
	}
	else if(DIO_u8GetPinVal(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_4_PIN) == DIO_U8_LOW)
	{
		LOCAL_u8Button = KEYPAD_U8_C2R4;
	}

	DIO_voidSetPinVal(KEYPAD_U8_COL_PORT,KEYPAD_U8_COL_1_PIN,DIO_U8_HIGH);
	DIO_voidSetPinVal(KEYPAD_U8_COL_PORT,KEYPAD_U8_COL_2_PIN,DIO_U8_HIGH);
	DIO_voidSetPinVal(KEYPAD_U8_COL_PORT,KEYPAD_U8_COL_3_PIN,DIO_U8_LOW);
	DIO_voidSetPinVal(KEYPAD_U8_COL_PORT,KEYPAD_U8_COL_4_PIN,DIO_U8_HIGH);
	if(DIO_u8GetPinVal(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_1_PIN) == DIO_U8_LOW)
	{
		LOCAL_u8Button = KEYPAD_U8_C3R1;
	}
	else if(DIO_u8GetPinVal(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_2_PIN) == DIO_U8_LOW)
	{
		LOCAL_u8Button = KEYPAD_U8_C3R2;
	}
	else if(DIO_u8GetPinVal(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_3_PIN) == DIO_U8_LOW)
	{
		LOCAL_u8Button = KEYPAD_U8_C3R3;
	}
	else if(DIO_u8GetPinVal(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_4_PIN) == DIO_U8_LOW)
	{
		LOCAL_u8Button = KEYPAD_U8_C3R4;
	}
	
	DIO_voidSetPinVal(KEYPAD_U8_COL_PORT,KEYPAD_U8_COL_1_PIN,DIO_U8_HIGH);
	DIO_voidSetPinVal(KEYPAD_U8_COL_PORT,KEYPAD_U8_COL_2_PIN,DIO_U8_HIGH);
	DIO_voidSetPinVal(KEYPAD_U8_COL_PORT,KEYPAD_U8_COL_3_PIN,DIO_U8_HIGH);
	DIO_voidSetPinVal(KEYPAD_U8_COL_PORT,KEYPAD_U8_COL_4_PIN,DIO_U8_LOW);
	if(DIO_u8GetPinVal(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_1_PIN) == DIO_U8_LOW)
	{
		LOCAL_u8Button = KEYPAD_U8_C4R1;
	}
	else if(DIO_u8GetPinVal(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_2_PIN) == DIO_U8_LOW)
	{
		LOCAL_u8Button = KEYPAD_U8_C4R2;
	}
	else if(DIO_u8GetPinVal(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_3_PIN) == DIO_U8_LOW)
	{
		LOCAL_u8Button = KEYPAD_U8_C4R3;
	}
	else if(DIO_u8GetPinVal(KEYPAD_U8_ROW_PORT,KEYPAD_U8_ROW_4_PIN) == DIO_U8_LOW)
	{
		LOCAL_u8Button = KEYPAD_U8_C4R4;
	}
	
	
	return LOCAL_u8Button;
}